# Generated by Django 3.2 on 2021-04-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='TextBox',
            new_name='textBox',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='Wirter',
            new_name='wirter',
        ),
        migrations.RemoveField(
            model_name='content',
            name='Date',
        ),
        migrations.AlterField(
            model_name='content',
            name='Id_M',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='community.category'),
        ),
    ]
