# Generated by Django 3.2 on 2021-04-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210428_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='wirter',
            new_name='name',
        ),
    ]
