# Generated by Django 3.2 on 2021-04-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210429_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Lists',
            new_name='lists',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Title',
            new_name='title',
        ),
    ]
