# Generated by Django 3.2.1 on 2021-05-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20210429_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Id_M',
            new_name='category',
        ),
    ]
