# Generated by Django 3.2.1 on 2021-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20210507_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpro',
            name='password',
            field=models.CharField(default=False, max_length=64),
        ),
        migrations.AddField(
            model_name='userpro',
            name='username',
            field=models.CharField(default=False, max_length=64),
        ),
    ]
