# Generated by Django 3.2.1 on 2021-05-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_userpro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Id_M',
        ),
    ]
