# Generated by Django 3.2.1 on 2021-05-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_remove_category_id_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userpro',
            name='username',
        ),
    ]
