# Generated by Django 3.2.1 on 2021-05-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_auto_20210507_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userpro',
            name='username',
        ),
    ]
