# Generated by Django 3.2.1 on 2021-05-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20210511_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cotent',
            new_name='content',
        ),
    ]
