# Generated by Django 3.2.1 on 2021-05-13 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0020_rename_cotent_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='user_pro',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_comments', to='community.userpro'),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pro', to=settings.AUTH_USER_MODEL),
        ),
    ]
